**AIM:** Matrix operations (using vectorization) and transformation using python and SVD 
using Python.

---



In [ ]:
import numpy as np

list=[1,2,3,4]
np.array(list)

list2=[[5,6,7],[6,9,2],[4,1,0]]
np.array(list2)

np.arange(0,10)
np.arange(0,11,2)
np.zeros(3)
np.zeros((3,3))
np.ones(3)
np.ones((3,3))
np.eye(3)
np.linspace(0,3,6)
np.linspace(0,10,100)
np.random.rand(3)
np.random.rand(3,4)
np.random.randn(3)
np.random.randint(4,8,2)

l=np.arange(0,25)
l.reshape(5,5)
l.max()
l.min()
l.argmax()
l.argmin()
l.shape
l.reshape(25,1)
l.dtype

k=[[5,10,15],[20,25,30],[35,40,45]]
arr1=np.array(k)
arr[1]
arr[1:3]
arr[1:2]=40 
arr[:]=40

arr1[1:3,0:2]

kk=arr1>20
arr1[kk]


array([25, 30, 35, 40, 45])

In [ ]:
import numpy as np
arr=np.arange(0,10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
import numpy as np
arr=np.arange(0,10)
arr-arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
import numpy as np
arr=np.arange(0,10)
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
import numpy as np
arr=np.arange(1,10)
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
import numpy as np
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
import numpy as np
p=np.ones(10)
p*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
v=np.arange(0,9)
v.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(1)

array([0.24755786])

In [ ]:
np.random.randint(1,50,25)

array([34, 14, 31, 45,  7, 13, 41, 23, 19, 40, 28, 46, 21,  4, 28, 19, 37,
       37, 16, 48, 30, 44, 35, 36, 24])

In [ ]:
np.random.randn(1,50,25)

array([[[ 1.18688187, -1.70700178,  0.17035755, ...,  0.5711001 ,
          0.44157757, -0.48563451],
        [ 2.68416045, -2.26052296, -0.6373825 , ...,  0.15754286,
         -1.38850735, -0.12517609],
        [ 0.34498954,  0.83732434,  0.22012037, ..., -0.67630064,
          0.57833026,  1.71487329],
        ...,
        [ 0.14307435, -1.01579976,  1.78315278, ..., -1.53829061,
          0.63752372,  2.06352542],
        [ 1.50823999,  1.46981708,  1.15593355, ..., -1.2438443 ,
         -0.05624566, -0.61311198],
        [-0.25238252,  1.29745184,  0.42063045, ..., -0.73120962,
         -0.09026772, -0.26689036]]])

In [ ]:
np.random.randn(5,5)

array([[ 0.27427343, -0.3936216 , -0.24161988,  1.1306362 ,  0.20885342],
       [ 0.48334986,  0.17678237, -1.75388344,  1.31549175,  0.8202483 ],
       [-0.55361097, -1.91100408, -0.08974947,  0.23002296,  0.18504579],
       [ 2.05169853, -0.93104649, -1.51315819, -0.08510949,  0.43158241],
       [-0.71816848,  1.20656901, -0.06900509,  0.3184274 ,  0.63255383]])

In [ ]:
ar=np.arange(1,101)
d=ar.reshape(10,10)
d/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
p=np.arange(1,26).reshape(5,5)
p

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
p[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
p[3,4]

20

In [ ]:
p[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
p[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
p[4:]

array([[21, 22, 23, 24, 25]])

In [ ]:
p.sum()

325

In [ ]:
p.std()

7.211102550927978

In [ ]:
l=np.arange(1,26).reshape(5,5)
l.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
arr = array([[2, 3], [4, 5], [6, 7]])
print(arr)
# SVD
U, s, VT = svd(arr)
print(U) 
print(s)
print(VT)

[[2 3]
 [4 5]
 [6 7]]
[[-0.30449857  0.86058931  0.40824829]
 [-0.54340036  0.1950625  -0.81649658]
 [-0.78230216 -0.47046431  0.40824829]]
[11.78249223  0.41578466]
[[-0.63453566 -0.77289358]
 [-0.77289358  0.63453566]]


In [ ]:
U, s, VT = svd(arr,full_matrices=True)
print(U) 
print(s)
print(VT)

[[-0.30449857  0.86058931  0.40824829]
 [-0.54340036  0.1950625  -0.81649658]
 [-0.78230216 -0.47046431  0.40824829]]
[11.78249223  0.41578466]
[[-0.63453566 -0.77289358]
 [-0.77289358  0.63453566]]


In [ ]:
U, s, VT = svd(arr,full_matrices=False)
print(U) 
print(s)
print(VT)

[[-0.30449857  0.86058931]
 [-0.54340036  0.1950625 ]
 [-0.78230216 -0.47046431]]
[11.78249223  0.41578466]
[[-0.63453566 -0.77289358]
 [-0.77289358  0.63453566]]


In [ ]:
from numpy import diag
from numpy import dot
from numpy import zeros
print(arr)
# Singular-value decomposition
U, s, VT = svd(arr)
# create m x n Sigma matrix
Sigma = zeros((arr.shape[0], arr.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:arr.shape[1], :arr.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[2 3]
 [4 5]
 [6 7]]
[[2. 3.]
 [4. 5.]
 [6. 7.]]


In [ ]:
import numpy as np
arr = np.array([[1,9,2],[3,8,7],[2,5,6]])
U, D, VT = np.linalg.svd(arr)
#Checking if we can remake the original matrix using U,D,VT
arr_remake = (U @ np.diag(D) @ VT)
print(arr_remake)

[[1. 9. 2.]
 [3. 8. 7.]
 [2. 5. 6.]]


**RESULT**: Program is executed successfully and output is obtained