In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dt=pd.read_csv('/content/sample_data/Iris.csv')

In [ ]:
dt

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
sc.fit(dt.drop('Species',axis=1))

In [ ]:
st=sc.transform(dt.drop('Species',axis=1))


In [ ]:
st

In [ ]:
new_dt=pd.DataFrame(st,columns=dt.columns[:-1])

In [ ]:
new_dt

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=new_dt
y=dt['Species']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,CategoricalNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [ ]:
scores=[]
classifier=GaussianNB()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
scores.append(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
cm

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

In [ ]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
1.0
